services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow

  airflow-init:
    build:
      context: .
      dockerfile: Dockerfile
    image: airflow-custom:latest
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      PYTHONPATH: /opt/airflow:/opt/airflow/src
    entrypoint: >
      bash -c "
        airflow db migrate &&
        airflow users create -r Admin -u admin -p admin -e admin@example.com -f admin -l airflow
      "
    volumes:
      - ./:/opt/airflow
      - ./src:/opt/airflow/src             # ✅ MOUNTED YOUR SRC DIRECTORY
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./notebooks:/opt/airflow/notebooks

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile
    image: airflow-custom:latest
    ports:
      - "8086:8080"
    depends_on:
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      PYTHONPATH: /opt/airflow:/opt/airflow/src
    volumes:
      - ./:/opt/airflow
      - ./src:/opt/airflow/src             # ✅ MOUNTED YOUR SRC DIRECTORY
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./notebooks:/opt/airflow/notebooks
    command: webserver

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    image: airflow-custom:latest
    depends_on:
      - airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      PYTHONPATH: /opt/airflow:/opt/airflow/src
    volumes:
      - ./:/opt/airflow
      - ./src:/opt/airflow/src             # ✅ MOUNTED YOUR SRC DIRECTORY
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./notebooks:/opt/airflow/notebooks
    command: scheduler
